/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#0f1512",
        foreground: "hsl(var(--foreground))",
        // Editorial Obsidian Academic Palette
        surface: "#0f1512",
        "surface-dim": "#0f1512",
        "surface-bright": "#343b37",
        "surface-container-lowest": "#090f0c",
        "surface-container-low": "#171d1a",
        "surface-container": "#1b211e",
        "surface-container-high": "#252b28",
        "surface-container-highest": "#303632",
        "on-surface": "#dee4de",
        "on-surface-variant": "#bbcabf",
        "inverse-surface": "#dee4de",
        "inverse-on-surface": "#2b322e",
        outline: "#86948a",
        "outline-variant": "#3c4a42",
        "surface-tint": "#4edea3",
        primary: "#4edea3",
        "on-primary": "#003824",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "inverse-primary": "#006c49",
        secondary: "#8ed6aa",
        "on-secondary": "#003921",
        "secondary-container": "#005433",
        "on-secondary-container": "#80c79d",
        tertiary: "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#e29100",
        "on-tertiary-container": "#523200",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed": "#a9f3c5",
        "secondary-fixed-dim": "#8ed6aa",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005232",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "on-background": "#dee4de",
        "surface-variant": "#303632",
        // BJTU Jiaotong Legacy Palette
        bjtu: {
          50: "#f0f4fa",
          100: "#e0eaf4",
          200: "#c8d9eb",
          300: "#a3c0de",
          400: "#75a1cd",
          500: "#5083bc",
          600: "#3d6aa4",
          700: "#315486",
          800: "#1e3a63",
          900: "#0b254a",
          950: "#061730",
        },
        academic: {
          50: "#f0f4fa",
          100: "#e0eaf4",
          200: "#c8d9eb",
          300: "#a3c0de",
          400: "#5083bc",
          500: "#315486",
          600: "#1e3a63",
          700: "#0b254a",
          800: "#061730",
          900: "#030d1d",
          950: "#01070f",
        },
      },
      spacing: {
        "container-max": "1440px",
        "unit-2xs": "0.25rem",
        "unit-xs": "0.5rem",
        "unit-sm": "0.75rem",
        "unit-md": "1rem",
        "unit-lg": "1.5rem",
        "unit-xl": "2rem",
        "unit-2xl": "3rem",
        "unit-3xl": "4rem",
        "unit-4xl": "6rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-xl": ["Newsreader", "Georgia", "serif"],
        "label-code": ["'Space Grotesk'", "monospace"],
        "display-hero": ["Newsreader", "Georgia", "serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "Georgia", "serif"],
        "headline-md": ["Newsreader", "Georgia", "serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-editorial": ["Newsreader", "Georgia", "serif"],
        "label-badge": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["Newsreader", "Georgia", "serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["Newsreader", "Georgia", "serif"],
        sans: [
          "'Plus Jakarta Sans'",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.03em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "title-editorial": ["22px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
